[package]
name = "avgcol"
version = "0.2.0"
description = "Quickly generate average colours for your images"
authors = ["Juliette Cordor"]
edition = "2021"

[features]
remote_image = ["reqwest"]

[dependencies]
base64 = "0.13.0"
image = "0.24.2"

reqwest = { version = "0.11.10", optional = true }
thiserror = "1.0.37"

